Updates to Makefile for a debian cross build
--- a/Makefile
+++ b/Makefile
@@ -1,3 +1,15 @@
+# CC ?= gcc
 
+.PHONY: install clean
 
 all: pxaregs
+
+
+$(DESTDIR)/usr/bin/pxaregs: pxaregs
+	install -d $(@D)
+	cp pxaregs $(@D)
+
+install: $(DESTDIR)/usr/bin/pxaregs
+
+clean:
+	rm -f *.o pxaregs *.rej *.orig
